package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Caracterizacionlote generated by hbm2java
 */
public class Caracterizacionlote implements java.io.Serializable {

	private BigDecimal carid;
	private Clasificaciontextura clasificaciontextura;
	private EstrategiaLote estrategiaLote;
	private Faseaplicada faseaplicada;
	private Set<Medicionmetricas> medicionmetricases = new HashSet<Medicionmetricas>(0);
	private Set<EstrategiaLote> estrategiaLotes = new HashSet<EstrategiaLote>(0);
	private Set<Medicionelemento> medicionelementos = new HashSet<Medicionelemento>(0);

	public Caracterizacionlote() {
	}

	public Caracterizacionlote(BigDecimal carid, EstrategiaLote estrategiaLote) {
		this.carid = carid;
		this.estrategiaLote = estrategiaLote;
	}

	public Caracterizacionlote(BigDecimal carid, Clasificaciontextura clasificaciontextura,
			EstrategiaLote estrategiaLote, Faseaplicada faseaplicada, Set<Medicionmetricas> medicionmetricases,
			Set<EstrategiaLote> estrategiaLotes, Set<Medicionelemento> medicionelementos) {
		this.carid = carid;
		this.clasificaciontextura = clasificaciontextura;
		this.estrategiaLote = estrategiaLote;
		this.faseaplicada = faseaplicada;
		this.medicionmetricases = medicionmetricases;
		this.estrategiaLotes = estrategiaLotes;
		this.medicionelementos = medicionelementos;
	}

	public BigDecimal getCarid() {
		return this.carid;
	}

	public void setCarid(BigDecimal carid) {
		this.carid = carid;
	}

	public Clasificaciontextura getClasificaciontextura() {
		return this.clasificaciontextura;
	}

	public void setClasificaciontextura(Clasificaciontextura clasificaciontextura) {
		this.clasificaciontextura = clasificaciontextura;
	}

	public EstrategiaLote getEstrategiaLote() {
		return this.estrategiaLote;
	}

	public void setEstrategiaLote(EstrategiaLote estrategiaLote) {
		this.estrategiaLote = estrategiaLote;
	}

	public Faseaplicada getFaseaplicada() {
		return this.faseaplicada;
	}

	public void setFaseaplicada(Faseaplicada faseaplicada) {
		this.faseaplicada = faseaplicada;
	}

	public Set<Medicionmetricas> getMedicionmetricases() {
		return this.medicionmetricases;
	}

	public void setMedicionmetricases(Set<Medicionmetricas> medicionmetricases) {
		this.medicionmetricases = medicionmetricases;
	}

	public Set<EstrategiaLote> getEstrategiaLotes() {
		return this.estrategiaLotes;
	}

	public void setEstrategiaLotes(Set<EstrategiaLote> estrategiaLotes) {
		this.estrategiaLotes = estrategiaLotes;
	}

	public Set<Medicionelemento> getMedicionelementos() {
		return this.medicionelementos;
	}

	public void setMedicionelementos(Set<Medicionelemento> medicionelementos) {
		this.medicionelementos = medicionelementos;
	}

}
