package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Clasificacionelemento generated by hbm2java
 */
public class Clasificacionelemento implements java.io.Serializable {

	private BigDecimal claelemfid;
	private String nombre;
	private Set<Elemento> elementos = new HashSet<Elemento>(0);

	public Clasificacionelemento() {
	}

	public Clasificacionelemento(BigDecimal claelemfid, String nombre) {
		this.claelemfid = claelemfid;
		this.nombre = nombre;
	}

	public Clasificacionelemento(BigDecimal claelemfid, String nombre, Set<Elemento> elementos) {
		this.claelemfid = claelemfid;
		this.nombre = nombre;
		this.elementos = elementos;
	}

	public BigDecimal getClaelemfid() {
		return this.claelemfid;
	}

	public void setClaelemfid(BigDecimal claelemfid) {
		this.claelemfid = claelemfid;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Elemento> getElementos() {
		return this.elementos;
	}

	public void setElementos(Set<Elemento> elementos) {
		this.elementos = elementos;
	}

}
