package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Elemento generated by hbm2java
 */
public class Elemento implements java.io.Serializable {

	private BigDecimal elemid;
	private Clasificacionelemento clasificacionelemento;
	private String nombreelem;
	private String simbolo;
	private Set<Rangoelementos> rangoelementoses = new HashSet<Rangoelementos>(0);

	public Elemento() {
	}

	public Elemento(BigDecimal elemid, String nombreelem, String simbolo) {
		this.elemid = elemid;
		this.nombreelem = nombreelem;
		this.simbolo = simbolo;
	}

	public Elemento(BigDecimal elemid, Clasificacionelemento clasificacionelemento, String nombreelem, String simbolo,
			Set<Rangoelementos> rangoelementoses) {
		this.elemid = elemid;
		this.clasificacionelemento = clasificacionelemento;
		this.nombreelem = nombreelem;
		this.simbolo = simbolo;
		this.rangoelementoses = rangoelementoses;
	}

	public BigDecimal getElemid() {
		return this.elemid;
	}

	public void setElemid(BigDecimal elemid) {
		this.elemid = elemid;
	}

	public Clasificacionelemento getClasificacionelemento() {
		return this.clasificacionelemento;
	}

	public void setClasificacionelemento(Clasificacionelemento clasificacionelemento) {
		this.clasificacionelemento = clasificacionelemento;
	}

	public String getNombreelem() {
		return this.nombreelem;
	}

	public void setNombreelem(String nombreelem) {
		this.nombreelem = nombreelem;
	}

	public String getSimbolo() {
		return this.simbolo;
	}

	public void setSimbolo(String simbolo) {
		this.simbolo = simbolo;
	}

	public Set<Rangoelementos> getRangoelementoses() {
		return this.rangoelementoses;
	}

	public void setRangoelementoses(Set<Rangoelementos> rangoelementoses) {
		this.rangoelementoses = rangoelementoses;
	}

}
