package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EstrategiaLote generated by hbm2java
 */
public class EstrategiaLote implements java.io.Serializable {

	private BigDecimal estrategialoteid;
	private Caracterizacionlote caracterizacionlote;
	private Estrategiamuestreo estrategiamuestreo;
	private Lote lote;
	private long numeropuntos;
	private Set<Caracterizacionlote> caracterizacionlotes = new HashSet<Caracterizacionlote>(0);
	private Set<Puntorecoleccion> puntorecoleccions = new HashSet<Puntorecoleccion>(0);

	public EstrategiaLote() {
	}

	public EstrategiaLote(BigDecimal estrategialoteid, long numeropuntos) {
		this.estrategialoteid = estrategialoteid;
		this.numeropuntos = numeropuntos;
	}

	public EstrategiaLote(BigDecimal estrategialoteid, Caracterizacionlote caracterizacionlote,
			Estrategiamuestreo estrategiamuestreo, Lote lote, long numeropuntos,
			Set<Caracterizacionlote> caracterizacionlotes, Set<Puntorecoleccion> puntorecoleccions) {
		this.estrategialoteid = estrategialoteid;
		this.caracterizacionlote = caracterizacionlote;
		this.estrategiamuestreo = estrategiamuestreo;
		this.lote = lote;
		this.numeropuntos = numeropuntos;
		this.caracterizacionlotes = caracterizacionlotes;
		this.puntorecoleccions = puntorecoleccions;
	}

	public BigDecimal getEstrategialoteid() {
		return this.estrategialoteid;
	}

	public void setEstrategialoteid(BigDecimal estrategialoteid) {
		this.estrategialoteid = estrategialoteid;
	}

	public Caracterizacionlote getCaracterizacionlote() {
		return this.caracterizacionlote;
	}

	public void setCaracterizacionlote(Caracterizacionlote caracterizacionlote) {
		this.caracterizacionlote = caracterizacionlote;
	}

	public Estrategiamuestreo getEstrategiamuestreo() {
		return this.estrategiamuestreo;
	}

	public void setEstrategiamuestreo(Estrategiamuestreo estrategiamuestreo) {
		this.estrategiamuestreo = estrategiamuestreo;
	}

	public Lote getLote() {
		return this.lote;
	}

	public void setLote(Lote lote) {
		this.lote = lote;
	}

	public long getNumeropuntos() {
		return this.numeropuntos;
	}

	public void setNumeropuntos(long numeropuntos) {
		this.numeropuntos = numeropuntos;
	}

	public Set<Caracterizacionlote> getCaracterizacionlotes() {
		return this.caracterizacionlotes;
	}

	public void setCaracterizacionlotes(Set<Caracterizacionlote> caracterizacionlotes) {
		this.caracterizacionlotes = caracterizacionlotes;
	}

	public Set<Puntorecoleccion> getPuntorecoleccions() {
		return this.puntorecoleccions;
	}

	public void setPuntorecoleccions(Set<Puntorecoleccion> puntorecoleccions) {
		this.puntorecoleccions = puntorecoleccions;
	}

}
