package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estrategiamuestreo generated by hbm2java
 */
public class Estrategiamuestreo implements java.io.Serializable {

	private BigDecimal planmid;
	private Diagnosticoagronomo diagnosticoagronomo;
	private Informelaboratorio informelaboratorio;
	private Terreno terreno;
	private String codigoest;
	private Date fechacreacion;
	private Set<Diagnosticoagronomo> diagnosticoagronomos = new HashSet<Diagnosticoagronomo>(0);
	private Set<EstrategiaLote> estrategiaLotes = new HashSet<EstrategiaLote>(0);
	private Set<Informelaboratorio> informelaboratorios = new HashSet<Informelaboratorio>(0);

	public Estrategiamuestreo() {
	}

	public Estrategiamuestreo(BigDecimal planmid, String codigoest, Date fechacreacion) {
		this.planmid = planmid;
		this.codigoest = codigoest;
		this.fechacreacion = fechacreacion;
	}

	public Estrategiamuestreo(BigDecimal planmid, Diagnosticoagronomo diagnosticoagronomo,
			Informelaboratorio informelaboratorio, Terreno terreno, String codigoest, Date fechacreacion,
			Set<Diagnosticoagronomo> diagnosticoagronomos, Set<EstrategiaLote> estrategiaLotes,
			Set<Informelaboratorio> informelaboratorios) {
		this.planmid = planmid;
		this.diagnosticoagronomo = diagnosticoagronomo;
		this.informelaboratorio = informelaboratorio;
		this.terreno = terreno;
		this.codigoest = codigoest;
		this.fechacreacion = fechacreacion;
		this.diagnosticoagronomos = diagnosticoagronomos;
		this.estrategiaLotes = estrategiaLotes;
		this.informelaboratorios = informelaboratorios;
	}

	public BigDecimal getPlanmid() {
		return this.planmid;
	}

	public void setPlanmid(BigDecimal planmid) {
		this.planmid = planmid;
	}

	public Diagnosticoagronomo getDiagnosticoagronomo() {
		return this.diagnosticoagronomo;
	}

	public void setDiagnosticoagronomo(Diagnosticoagronomo diagnosticoagronomo) {
		this.diagnosticoagronomo = diagnosticoagronomo;
	}

	public Informelaboratorio getInformelaboratorio() {
		return this.informelaboratorio;
	}

	public void setInformelaboratorio(Informelaboratorio informelaboratorio) {
		this.informelaboratorio = informelaboratorio;
	}

	public Terreno getTerreno() {
		return this.terreno;
	}

	public void setTerreno(Terreno terreno) {
		this.terreno = terreno;
	}

	public String getCodigoest() {
		return this.codigoest;
	}

	public void setCodigoest(String codigoest) {
		this.codigoest = codigoest;
	}

	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public Set<Diagnosticoagronomo> getDiagnosticoagronomos() {
		return this.diagnosticoagronomos;
	}

	public void setDiagnosticoagronomos(Set<Diagnosticoagronomo> diagnosticoagronomos) {
		this.diagnosticoagronomos = diagnosticoagronomos;
	}

	public Set<EstrategiaLote> getEstrategiaLotes() {
		return this.estrategiaLotes;
	}

	public void setEstrategiaLotes(Set<EstrategiaLote> estrategiaLotes) {
		this.estrategiaLotes = estrategiaLotes;
	}

	public Set<Informelaboratorio> getInformelaboratorios() {
		return this.informelaboratorios;
	}

	public void setInformelaboratorios(Set<Informelaboratorio> informelaboratorios) {
		this.informelaboratorios = informelaboratorios;
	}

}
