package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Familiatextural generated by hbm2java
 */
public class Familiatextural implements java.io.Serializable {

	private BigDecimal familiatexid;
	private Grupotextural grupotextural;
	private String nombrefamtext;
	private String abreviaturafamtext;
	private Set<GrupohomosueloFamiliatextural> grupohomosueloFamiliatexturals = new HashSet<GrupohomosueloFamiliatextural>(
			0);

	public Familiatextural() {
	}

	public Familiatextural(BigDecimal familiatexid, String nombrefamtext, String abreviaturafamtext) {
		this.familiatexid = familiatexid;
		this.nombrefamtext = nombrefamtext;
		this.abreviaturafamtext = abreviaturafamtext;
	}

	public Familiatextural(BigDecimal familiatexid, Grupotextural grupotextural, String nombrefamtext,
			String abreviaturafamtext, Set<GrupohomosueloFamiliatextural> grupohomosueloFamiliatexturals) {
		this.familiatexid = familiatexid;
		this.grupotextural = grupotextural;
		this.nombrefamtext = nombrefamtext;
		this.abreviaturafamtext = abreviaturafamtext;
		this.grupohomosueloFamiliatexturals = grupohomosueloFamiliatexturals;
	}

	public BigDecimal getFamiliatexid() {
		return this.familiatexid;
	}

	public void setFamiliatexid(BigDecimal familiatexid) {
		this.familiatexid = familiatexid;
	}

	public Grupotextural getGrupotextural() {
		return this.grupotextural;
	}

	public void setGrupotextural(Grupotextural grupotextural) {
		this.grupotextural = grupotextural;
	}

	public String getNombrefamtext() {
		return this.nombrefamtext;
	}

	public void setNombrefamtext(String nombrefamtext) {
		this.nombrefamtext = nombrefamtext;
	}

	public String getAbreviaturafamtext() {
		return this.abreviaturafamtext;
	}

	public void setAbreviaturafamtext(String abreviaturafamtext) {
		this.abreviaturafamtext = abreviaturafamtext;
	}

	public Set<GrupohomosueloFamiliatextural> getGrupohomosueloFamiliatexturals() {
		return this.grupohomosueloFamiliatexturals;
	}

	public void setGrupohomosueloFamiliatexturals(Set<GrupohomosueloFamiliatextural> grupohomosueloFamiliatexturals) {
		this.grupohomosueloFamiliatexturals = grupohomosueloFamiliatexturals;
	}

}
