package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Faseaplicada generated by hbm2java
 */
public class Faseaplicada implements java.io.Serializable {

	private BigDecimal faseid;
	private String nombrefase;
	private Set<Caracterizacionlote> caracterizacionlotes = new HashSet<Caracterizacionlote>(0);

	public Faseaplicada() {
	}

	public Faseaplicada(BigDecimal faseid, String nombrefase) {
		this.faseid = faseid;
		this.nombrefase = nombrefase;
	}

	public Faseaplicada(BigDecimal faseid, String nombrefase, Set<Caracterizacionlote> caracterizacionlotes) {
		this.faseid = faseid;
		this.nombrefase = nombrefase;
		this.caracterizacionlotes = caracterizacionlotes;
	}

	public BigDecimal getFaseid() {
		return this.faseid;
	}

	public void setFaseid(BigDecimal faseid) {
		this.faseid = faseid;
	}

	public String getNombrefase() {
		return this.nombrefase;
	}

	public void setNombrefase(String nombrefase) {
		this.nombrefase = nombrefase;
	}

	public Set<Caracterizacionlote> getCaracterizacionlotes() {
		return this.caracterizacionlotes;
	}

	public void setCaracterizacionlotes(Set<Caracterizacionlote> caracterizacionlotes) {
		this.caracterizacionlotes = caracterizacionlotes;
	}

}
