package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * GrupohomosueloCaracteristica generated by hbm2java
 */
public class GrupohomosueloCaracteristica implements java.io.Serializable {

	private BigDecimal id;
	private Caracteristica caracteristica;
	private Grupohomogeneosuelo grupohomogeneosuelo;

	public GrupohomosueloCaracteristica() {
	}

	public GrupohomosueloCaracteristica(BigDecimal id) {
		this.id = id;
	}

	public GrupohomosueloCaracteristica(BigDecimal id, Caracteristica caracteristica,
			Grupohomogeneosuelo grupohomogeneosuelo) {
		this.id = id;
		this.caracteristica = caracteristica;
		this.grupohomogeneosuelo = grupohomogeneosuelo;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Caracteristica getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(Caracteristica caracteristica) {
		this.caracteristica = caracteristica;
	}

	public Grupohomogeneosuelo getGrupohomogeneosuelo() {
		return this.grupohomogeneosuelo;
	}

	public void setGrupohomogeneosuelo(Grupohomogeneosuelo grupohomogeneosuelo) {
		this.grupohomogeneosuelo = grupohomogeneosuelo;
	}

}
