package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupotextural generated by hbm2java
 */
public class Grupotextural implements java.io.Serializable {

	private BigDecimal grupotextid;
	private String numerogrupotext;
	private Set<Familiatextural> familiatexturals = new HashSet<Familiatextural>(0);

	public Grupotextural() {
	}

	public Grupotextural(BigDecimal grupotextid, String numerogrupotext) {
		this.grupotextid = grupotextid;
		this.numerogrupotext = numerogrupotext;
	}

	public Grupotextural(BigDecimal grupotextid, String numerogrupotext, Set<Familiatextural> familiatexturals) {
		this.grupotextid = grupotextid;
		this.numerogrupotext = numerogrupotext;
		this.familiatexturals = familiatexturals;
	}

	public BigDecimal getGrupotextid() {
		return this.grupotextid;
	}

	public void setGrupotextid(BigDecimal grupotextid) {
		this.grupotextid = grupotextid;
	}

	public String getNumerogrupotext() {
		return this.numerogrupotext;
	}

	public void setNumerogrupotext(String numerogrupotext) {
		this.numerogrupotext = numerogrupotext;
	}

	public Set<Familiatextural> getFamiliatexturals() {
		return this.familiatexturals;
	}

	public void setFamiliatexturals(Set<Familiatextural> familiatexturals) {
		this.familiatexturals = familiatexturals;
	}

}
