package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * GrupohomosueloOrdensuelo generated by hbm2java
 */
public class GrupohomosueloOrdensuelo implements java.io.Serializable {

	private BigDecimal id;
	private Grupohomogeneosuelo grupohomogeneosuelo;
	private Ordensuelo ordensuelo;
	private int numerosuelo;

	public GrupohomosueloOrdensuelo() {
	}

	public GrupohomosueloOrdensuelo(BigDecimal id, int numerosuelo) {
		this.id = id;
		this.numerosuelo = numerosuelo;
	}

	public GrupohomosueloOrdensuelo(BigDecimal id, Grupohomogeneosuelo grupohomogeneosuelo, Ordensuelo ordensuelo,
			int numerosuelo) {
		this.id = id;
		this.grupohomogeneosuelo = grupohomogeneosuelo;
		this.ordensuelo = ordensuelo;
		this.numerosuelo = numerosuelo;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Grupohomogeneosuelo getGrupohomogeneosuelo() {
		return this.grupohomogeneosuelo;
	}

	public void setGrupohomogeneosuelo(Grupohomogeneosuelo grupohomogeneosuelo) {
		this.grupohomogeneosuelo = grupohomogeneosuelo;
	}

	public Ordensuelo getOrdensuelo() {
		return this.ordensuelo;
	}

	public void setOrdensuelo(Ordensuelo ordensuelo) {
		this.ordensuelo = ordensuelo;
	}

	public int getNumerosuelo() {
		return this.numerosuelo;
	}

	public void setNumerosuelo(int numerosuelo) {
		this.numerosuelo = numerosuelo;
	}

}
