package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupohumedad generated by hbm2java
 */
public class Grupohumedad implements java.io.Serializable {

	private BigDecimal grupohumid;
	private String nombregrhum;
	private String siglasgrhum;
	private Set<Zonaagroecologica> zonaagroecologicas = new HashSet<Zonaagroecologica>(0);
	private Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums = new HashSet<NivelhumTipopermeaGrupohum>(0);

	public Grupohumedad() {
	}

	public Grupohumedad(BigDecimal grupohumid, String nombregrhum, String siglasgrhum) {
		this.grupohumid = grupohumid;
		this.nombregrhum = nombregrhum;
		this.siglasgrhum = siglasgrhum;
	}

	public Grupohumedad(BigDecimal grupohumid, String nombregrhum, String siglasgrhum,
			Set<Zonaagroecologica> zonaagroecologicas, Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums) {
		this.grupohumid = grupohumid;
		this.nombregrhum = nombregrhum;
		this.siglasgrhum = siglasgrhum;
		this.zonaagroecologicas = zonaagroecologicas;
		this.nivelhumTipopermeaGrupohums = nivelhumTipopermeaGrupohums;
	}

	public BigDecimal getGrupohumid() {
		return this.grupohumid;
	}

	public void setGrupohumid(BigDecimal grupohumid) {
		this.grupohumid = grupohumid;
	}

	public String getNombregrhum() {
		return this.nombregrhum;
	}

	public void setNombregrhum(String nombregrhum) {
		this.nombregrhum = nombregrhum;
	}

	public String getSiglasgrhum() {
		return this.siglasgrhum;
	}

	public void setSiglasgrhum(String siglasgrhum) {
		this.siglasgrhum = siglasgrhum;
	}

	public Set<Zonaagroecologica> getZonaagroecologicas() {
		return this.zonaagroecologicas;
	}

	public void setZonaagroecologicas(Set<Zonaagroecologica> zonaagroecologicas) {
		this.zonaagroecologicas = zonaagroecologicas;
	}

	public Set<NivelhumTipopermeaGrupohum> getNivelhumTipopermeaGrupohums() {
		return this.nivelhumTipopermeaGrupohums;
	}

	public void setNivelhumTipopermeaGrupohums(Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums) {
		this.nivelhumTipopermeaGrupohums = nivelhumTipopermeaGrupohums;
	}

}
