package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * GrupohomosueloFamiliatextural generated by hbm2java
 */
public class GrupohomosueloFamiliatextural implements java.io.Serializable {

	private BigDecimal id;
	private Familiatextural familiatextural;
	private Grupohomogeneosuelo grupohomogeneosuelo;

	public GrupohomosueloFamiliatextural() {
	}

	public GrupohomosueloFamiliatextural(BigDecimal id) {
		this.id = id;
	}

	public GrupohomosueloFamiliatextural(BigDecimal id, Familiatextural familiatextural,
			Grupohomogeneosuelo grupohomogeneosuelo) {
		this.id = id;
		this.familiatextural = familiatextural;
		this.grupohomogeneosuelo = grupohomogeneosuelo;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Familiatextural getFamiliatextural() {
		return this.familiatextural;
	}

	public void setFamiliatextural(Familiatextural familiatextural) {
		this.familiatextural = familiatextural;
	}

	public Grupohomogeneosuelo getGrupohomogeneosuelo() {
		return this.grupohomogeneosuelo;
	}

	public void setGrupohomogeneosuelo(Grupohomogeneosuelo grupohomogeneosuelo) {
		this.grupohomogeneosuelo = grupohomogeneosuelo;
	}

}
