package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Informelaboratorio generated by hbm2java
 */
public class Informelaboratorio implements java.io.Serializable {

	private BigDecimal informeid;
	private Estrategiamuestreo estrategiamuestreo;
	private String nombrehacienda;
	private String nombrelaboratorio;
	private Date fechaexpedicionresultados;
	private Set<Estrategiamuestreo> estrategiamuestreos = new HashSet<Estrategiamuestreo>(0);

	public Informelaboratorio() {
	}

	public Informelaboratorio(BigDecimal informeid, Estrategiamuestreo estrategiamuestreo) {
		this.informeid = informeid;
		this.estrategiamuestreo = estrategiamuestreo;
	}

	public Informelaboratorio(BigDecimal informeid, Estrategiamuestreo estrategiamuestreo, String nombrehacienda,
			String nombrelaboratorio, Date fechaexpedicionresultados, Set<Estrategiamuestreo> estrategiamuestreos) {
		this.informeid = informeid;
		this.estrategiamuestreo = estrategiamuestreo;
		this.nombrehacienda = nombrehacienda;
		this.nombrelaboratorio = nombrelaboratorio;
		this.fechaexpedicionresultados = fechaexpedicionresultados;
		this.estrategiamuestreos = estrategiamuestreos;
	}

	public BigDecimal getInformeid() {
		return this.informeid;
	}

	public void setInformeid(BigDecimal informeid) {
		this.informeid = informeid;
	}

	public Estrategiamuestreo getEstrategiamuestreo() {
		return this.estrategiamuestreo;
	}

	public void setEstrategiamuestreo(Estrategiamuestreo estrategiamuestreo) {
		this.estrategiamuestreo = estrategiamuestreo;
	}

	public String getNombrehacienda() {
		return this.nombrehacienda;
	}

	public void setNombrehacienda(String nombrehacienda) {
		this.nombrehacienda = nombrehacienda;
	}

	public String getNombrelaboratorio() {
		return this.nombrelaboratorio;
	}

	public void setNombrelaboratorio(String nombrelaboratorio) {
		this.nombrelaboratorio = nombrelaboratorio;
	}

	public Date getFechaexpedicionresultados() {
		return this.fechaexpedicionresultados;
	}

	public void setFechaexpedicionresultados(Date fechaexpedicionresultados) {
		this.fechaexpedicionresultados = fechaexpedicionresultados;
	}

	public Set<Estrategiamuestreo> getEstrategiamuestreos() {
		return this.estrategiamuestreos;
	}

	public void setEstrategiamuestreos(Set<Estrategiamuestreo> estrategiamuestreos) {
		this.estrategiamuestreos = estrategiamuestreos;
	}

}
