package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ingenio generated by hbm2java
 */
public class Ingenio implements java.io.Serializable {

	private BigDecimal ingid;
	private String nombreing;
	private Set<ZonaagroecologicaIngenio> zonaagroecologicaIngenios = new HashSet<ZonaagroecologicaIngenio>(0);

	public Ingenio() {
	}

	public Ingenio(BigDecimal ingid, String nombreing) {
		this.ingid = ingid;
		this.nombreing = nombreing;
	}

	public Ingenio(BigDecimal ingid, String nombreing, Set<ZonaagroecologicaIngenio> zonaagroecologicaIngenios) {
		this.ingid = ingid;
		this.nombreing = nombreing;
		this.zonaagroecologicaIngenios = zonaagroecologicaIngenios;
	}

	public BigDecimal getIngid() {
		return this.ingid;
	}

	public void setIngid(BigDecimal ingid) {
		this.ingid = ingid;
	}

	public String getNombreing() {
		return this.nombreing;
	}

	public void setNombreing(String nombreing) {
		this.nombreing = nombreing;
	}

	public Set<ZonaagroecologicaIngenio> getZonaagroecologicaIngenios() {
		return this.zonaagroecologicaIngenios;
	}

	public void setZonaagroecologicaIngenios(Set<ZonaagroecologicaIngenio> zonaagroecologicaIngenios) {
		this.zonaagroecologicaIngenios = zonaagroecologicaIngenios;
	}

}
