package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Lote generated by hbm2java
 */
public class Lote implements java.io.Serializable {

	private BigDecimal loteid;
	private Terreno terreno;
	private String nombrelote;
	private String descripcionlote;
	private Set<EstrategiaLote> estrategiaLotes = new HashSet<EstrategiaLote>(0);

	public Lote() {
	}

	public Lote(BigDecimal loteid, String nombrelote, String descripcionlote) {
		this.loteid = loteid;
		this.nombrelote = nombrelote;
		this.descripcionlote = descripcionlote;
	}

	public Lote(BigDecimal loteid, Terreno terreno, String nombrelote, String descripcionlote,
			Set<EstrategiaLote> estrategiaLotes) {
		this.loteid = loteid;
		this.terreno = terreno;
		this.nombrelote = nombrelote;
		this.descripcionlote = descripcionlote;
		this.estrategiaLotes = estrategiaLotes;
	}

	public BigDecimal getLoteid() {
		return this.loteid;
	}

	public void setLoteid(BigDecimal loteid) {
		this.loteid = loteid;
	}

	public Terreno getTerreno() {
		return this.terreno;
	}

	public void setTerreno(Terreno terreno) {
		this.terreno = terreno;
	}

	public String getNombrelote() {
		return this.nombrelote;
	}

	public void setNombrelote(String nombrelote) {
		this.nombrelote = nombrelote;
	}

	public String getDescripcionlote() {
		return this.descripcionlote;
	}

	public void setDescripcionlote(String descripcionlote) {
		this.descripcionlote = descripcionlote;
	}

	public Set<EstrategiaLote> getEstrategiaLotes() {
		return this.estrategiaLotes;
	}

	public void setEstrategiaLotes(Set<EstrategiaLote> estrategiaLotes) {
		this.estrategiaLotes = estrategiaLotes;
	}

}
