package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * Medicionelemento generated by hbm2java
 */
public class Medicionelemento implements java.io.Serializable {

	private BigDecimal meleid;
	private Caracterizacionlote caracterizacionlote;
	private Metodologia metodologia;
	private Rangoelementos rangoelementos;
	private double ppm;
	private double porcentajesolubilidad;

	public Medicionelemento() {
	}

	public Medicionelemento(BigDecimal meleid, Rangoelementos rangoelementos, double ppm,
			double porcentajesolubilidad) {
		this.meleid = meleid;
		this.rangoelementos = rangoelementos;
		this.ppm = ppm;
		this.porcentajesolubilidad = porcentajesolubilidad;
	}

	public Medicionelemento(BigDecimal meleid, Caracterizacionlote caracterizacionlote, Metodologia metodologia,
			Rangoelementos rangoelementos, double ppm, double porcentajesolubilidad) {
		this.meleid = meleid;
		this.caracterizacionlote = caracterizacionlote;
		this.metodologia = metodologia;
		this.rangoelementos = rangoelementos;
		this.ppm = ppm;
		this.porcentajesolubilidad = porcentajesolubilidad;
	}

	public BigDecimal getMeleid() {
		return this.meleid;
	}

	public void setMeleid(BigDecimal meleid) {
		this.meleid = meleid;
	}

	public Caracterizacionlote getCaracterizacionlote() {
		return this.caracterizacionlote;
	}

	public void setCaracterizacionlote(Caracterizacionlote caracterizacionlote) {
		this.caracterizacionlote = caracterizacionlote;
	}

	public Metodologia getMetodologia() {
		return this.metodologia;
	}

	public void setMetodologia(Metodologia metodologia) {
		this.metodologia = metodologia;
	}

	public Rangoelementos getRangoelementos() {
		return this.rangoelementos;
	}

	public void setRangoelementos(Rangoelementos rangoelementos) {
		this.rangoelementos = rangoelementos;
	}

	public double getPpm() {
		return this.ppm;
	}

	public void setPpm(double ppm) {
		this.ppm = ppm;
	}

	public double getPorcentajesolubilidad() {
		return this.porcentajesolubilidad;
	}

	public void setPorcentajesolubilidad(double porcentajesolubilidad) {
		this.porcentajesolubilidad = porcentajesolubilidad;
	}

}
