package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Metodologia generated by hbm2java
 */
public class Metodologia implements java.io.Serializable {

	private BigDecimal metoid;
	private String nombremet;
	private Set<Medicionelemento> medicionelementos = new HashSet<Medicionelemento>(0);
	private Set<Medicionmetricas> medicionmetricases = new HashSet<Medicionmetricas>(0);

	public Metodologia() {
	}

	public Metodologia(BigDecimal metoid, String nombremet) {
		this.metoid = metoid;
		this.nombremet = nombremet;
	}

	public Metodologia(BigDecimal metoid, String nombremet, Set<Medicionelemento> medicionelementos,
			Set<Medicionmetricas> medicionmetricases) {
		this.metoid = metoid;
		this.nombremet = nombremet;
		this.medicionelementos = medicionelementos;
		this.medicionmetricases = medicionmetricases;
	}

	public BigDecimal getMetoid() {
		return this.metoid;
	}

	public void setMetoid(BigDecimal metoid) {
		this.metoid = metoid;
	}

	public String getNombremet() {
		return this.nombremet;
	}

	public void setNombremet(String nombremet) {
		this.nombremet = nombremet;
	}

	public Set<Medicionelemento> getMedicionelementos() {
		return this.medicionelementos;
	}

	public void setMedicionelementos(Set<Medicionelemento> medicionelementos) {
		this.medicionelementos = medicionelementos;
	}

	public Set<Medicionmetricas> getMedicionmetricases() {
		return this.medicionmetricases;
	}

	public void setMedicionmetricases(Set<Medicionmetricas> medicionmetricases) {
		this.medicionmetricases = medicionmetricases;
	}

}
