package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Metrica generated by hbm2java
 */
public class Metrica implements java.io.Serializable {

	private BigDecimal metrid;
	private String nombremet;
	private Set<Rangometricas> rangometricases = new HashSet<Rangometricas>(0);

	public Metrica() {
	}

	public Metrica(BigDecimal metrid, String nombremet) {
		this.metrid = metrid;
		this.nombremet = nombremet;
	}

	public Metrica(BigDecimal metrid, String nombremet, Set<Rangometricas> rangometricases) {
		this.metrid = metrid;
		this.nombremet = nombremet;
		this.rangometricases = rangometricases;
	}

	public BigDecimal getMetrid() {
		return this.metrid;
	}

	public void setMetrid(BigDecimal metrid) {
		this.metrid = metrid;
	}

	public String getNombremet() {
		return this.nombremet;
	}

	public void setNombremet(String nombremet) {
		this.nombremet = nombremet;
	}

	public Set<Rangometricas> getRangometricases() {
		return this.rangometricases;
	}

	public void setRangometricases(Set<Rangometricas> rangometricases) {
		this.rangometricases = rangometricases;
	}

}
