package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * NivelhumTipopermeaGrupohum generated by hbm2java
 */
public class NivelhumTipopermeaGrupohum implements java.io.Serializable {

	private BigDecimal id;
	private Grupohumedad grupohumedad;
	private Nivelhumedad nivelhumedad;
	private Tipopermeabilidad tipopermeabilidad;

	public NivelhumTipopermeaGrupohum() {
	}

	public NivelhumTipopermeaGrupohum(BigDecimal id) {
		this.id = id;
	}

	public NivelhumTipopermeaGrupohum(BigDecimal id, Grupohumedad grupohumedad, Nivelhumedad nivelhumedad,
			Tipopermeabilidad tipopermeabilidad) {
		this.id = id;
		this.grupohumedad = grupohumedad;
		this.nivelhumedad = nivelhumedad;
		this.tipopermeabilidad = tipopermeabilidad;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Grupohumedad getGrupohumedad() {
		return this.grupohumedad;
	}

	public void setGrupohumedad(Grupohumedad grupohumedad) {
		this.grupohumedad = grupohumedad;
	}

	public Nivelhumedad getNivelhumedad() {
		return this.nivelhumedad;
	}

	public void setNivelhumedad(Nivelhumedad nivelhumedad) {
		this.nivelhumedad = nivelhumedad;
	}

	public Tipopermeabilidad getTipopermeabilidad() {
		return this.tipopermeabilidad;
	}

	public void setTipopermeabilidad(Tipopermeabilidad tipopermeabilidad) {
		this.tipopermeabilidad = tipopermeabilidad;
	}

}
