package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Nivelhumedad generated by hbm2java
 */
public class Nivelhumedad implements java.io.Serializable {

	private BigDecimal nivelhumid;
	private String nombrenvhum;
	private String valorminimo;
	private String valormaximo;
	private Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums = new HashSet<NivelhumTipopermeaGrupohum>(0);

	public Nivelhumedad() {
	}

	public Nivelhumedad(BigDecimal nivelhumid, String nombrenvhum, String valorminimo, String valormaximo) {
		this.nivelhumid = nivelhumid;
		this.nombrenvhum = nombrenvhum;
		this.valorminimo = valorminimo;
		this.valormaximo = valormaximo;
	}

	public Nivelhumedad(BigDecimal nivelhumid, String nombrenvhum, String valorminimo, String valormaximo,
			Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums) {
		this.nivelhumid = nivelhumid;
		this.nombrenvhum = nombrenvhum;
		this.valorminimo = valorminimo;
		this.valormaximo = valormaximo;
		this.nivelhumTipopermeaGrupohums = nivelhumTipopermeaGrupohums;
	}

	public BigDecimal getNivelhumid() {
		return this.nivelhumid;
	}

	public void setNivelhumid(BigDecimal nivelhumid) {
		this.nivelhumid = nivelhumid;
	}

	public String getNombrenvhum() {
		return this.nombrenvhum;
	}

	public void setNombrenvhum(String nombrenvhum) {
		this.nombrenvhum = nombrenvhum;
	}

	public String getValorminimo() {
		return this.valorminimo;
	}

	public void setValorminimo(String valorminimo) {
		this.valorminimo = valorminimo;
	}

	public String getValormaximo() {
		return this.valormaximo;
	}

	public void setValormaximo(String valormaximo) {
		this.valormaximo = valormaximo;
	}

	public Set<NivelhumTipopermeaGrupohum> getNivelhumTipopermeaGrupohums() {
		return this.nivelhumTipopermeaGrupohums;
	}

	public void setNivelhumTipopermeaGrupohums(Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums) {
		this.nivelhumTipopermeaGrupohums = nivelhumTipopermeaGrupohums;
	}

}
