package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordensuelo generated by hbm2java
 */
public class Ordensuelo implements java.io.Serializable {

	private BigDecimal ordensueloid;
	private String nombreorden;
	private String descripcionorden;
	private Set<Subordensuelo> subordensuelos = new HashSet<Subordensuelo>(0);
	private Set<GrupohomosueloOrdensuelo> grupohomosueloOrdensuelos = new HashSet<GrupohomosueloOrdensuelo>(0);

	public Ordensuelo() {
	}

	public Ordensuelo(BigDecimal ordensueloid, String nombreorden, String descripcionorden) {
		this.ordensueloid = ordensueloid;
		this.nombreorden = nombreorden;
		this.descripcionorden = descripcionorden;
	}

	public Ordensuelo(BigDecimal ordensueloid, String nombreorden, String descripcionorden,
			Set<Subordensuelo> subordensuelos, Set<GrupohomosueloOrdensuelo> grupohomosueloOrdensuelos) {
		this.ordensueloid = ordensueloid;
		this.nombreorden = nombreorden;
		this.descripcionorden = descripcionorden;
		this.subordensuelos = subordensuelos;
		this.grupohomosueloOrdensuelos = grupohomosueloOrdensuelos;
	}

	public BigDecimal getOrdensueloid() {
		return this.ordensueloid;
	}

	public void setOrdensueloid(BigDecimal ordensueloid) {
		this.ordensueloid = ordensueloid;
	}

	public String getNombreorden() {
		return this.nombreorden;
	}

	public void setNombreorden(String nombreorden) {
		this.nombreorden = nombreorden;
	}

	public String getDescripcionorden() {
		return this.descripcionorden;
	}

	public void setDescripcionorden(String descripcionorden) {
		this.descripcionorden = descripcionorden;
	}

	public Set<Subordensuelo> getSubordensuelos() {
		return this.subordensuelos;
	}

	public void setSubordensuelos(Set<Subordensuelo> subordensuelos) {
		this.subordensuelos = subordensuelos;
	}

	public Set<GrupohomosueloOrdensuelo> getGrupohomosueloOrdensuelos() {
		return this.grupohomosueloOrdensuelos;
	}

	public void setGrupohomosueloOrdensuelos(Set<GrupohomosueloOrdensuelo> grupohomosueloOrdensuelos) {
		this.grupohomosueloOrdensuelos = grupohomosueloOrdensuelos;
	}

}
