package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rangoelementos generated by hbm2java
 */
public class Rangoelementos implements java.io.Serializable {

	private BigDecimal idrango;
	private Elemento elemento;
	private String nombrerango;
	private double ppmminimo;
	private double ppmmaximo;
	private Set<Medicionelemento> medicionelementos = new HashSet<Medicionelemento>(0);

	public Rangoelementos() {
	}

	public Rangoelementos(BigDecimal idrango, Elemento elemento, String nombrerango, double ppmminimo,
			double ppmmaximo) {
		this.idrango = idrango;
		this.elemento = elemento;
		this.nombrerango = nombrerango;
		this.ppmminimo = ppmminimo;
		this.ppmmaximo = ppmmaximo;
	}

	public Rangoelementos(BigDecimal idrango, Elemento elemento, String nombrerango, double ppmminimo, double ppmmaximo,
			Set<Medicionelemento> medicionelementos) {
		this.idrango = idrango;
		this.elemento = elemento;
		this.nombrerango = nombrerango;
		this.ppmminimo = ppmminimo;
		this.ppmmaximo = ppmmaximo;
		this.medicionelementos = medicionelementos;
	}

	public BigDecimal getIdrango() {
		return this.idrango;
	}

	public void setIdrango(BigDecimal idrango) {
		this.idrango = idrango;
	}

	public Elemento getElemento() {
		return this.elemento;
	}

	public void setElemento(Elemento elemento) {
		this.elemento = elemento;
	}

	public String getNombrerango() {
		return this.nombrerango;
	}

	public void setNombrerango(String nombrerango) {
		this.nombrerango = nombrerango;
	}

	public double getPpmminimo() {
		return this.ppmminimo;
	}

	public void setPpmminimo(double ppmminimo) {
		this.ppmminimo = ppmminimo;
	}

	public double getPpmmaximo() {
		return this.ppmmaximo;
	}

	public void setPpmmaximo(double ppmmaximo) {
		this.ppmmaximo = ppmmaximo;
	}

	public Set<Medicionelemento> getMedicionelementos() {
		return this.medicionelementos;
	}

	public void setMedicionelementos(Set<Medicionelemento> medicionelementos) {
		this.medicionelementos = medicionelementos;
	}

}
