package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Regimenhumedad generated by hbm2java
 */
public class Regimenhumedad implements java.io.Serializable {

	private BigDecimal regimenhumid;
	private String nombrereg;
	private String descripcionreg;
	private Set<Subordensuelo> subordensuelos = new HashSet<Subordensuelo>(0);

	public Regimenhumedad() {
	}

	public Regimenhumedad(BigDecimal regimenhumid, String nombrereg, String descripcionreg) {
		this.regimenhumid = regimenhumid;
		this.nombrereg = nombrereg;
		this.descripcionreg = descripcionreg;
	}

	public Regimenhumedad(BigDecimal regimenhumid, String nombrereg, String descripcionreg,
			Set<Subordensuelo> subordensuelos) {
		this.regimenhumid = regimenhumid;
		this.nombrereg = nombrereg;
		this.descripcionreg = descripcionreg;
		this.subordensuelos = subordensuelos;
	}

	public BigDecimal getRegimenhumid() {
		return this.regimenhumid;
	}

	public void setRegimenhumid(BigDecimal regimenhumid) {
		this.regimenhumid = regimenhumid;
	}

	public String getNombrereg() {
		return this.nombrereg;
	}

	public void setNombrereg(String nombrereg) {
		this.nombrereg = nombrereg;
	}

	public String getDescripcionreg() {
		return this.descripcionreg;
	}

	public void setDescripcionreg(String descripcionreg) {
		this.descripcionreg = descripcionreg;
	}

	public Set<Subordensuelo> getSubordensuelos() {
		return this.subordensuelos;
	}

	public void setSubordensuelos(Set<Subordensuelo> subordensuelos) {
		this.subordensuelos = subordensuelos;
	}

}
