package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private BigDecimal rolid;
	private String nombrerol;
	private String descripcionrol;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(BigDecimal rolid, String nombrerol, String descripcionrol) {
		this.rolid = rolid;
		this.nombrerol = nombrerol;
		this.descripcionrol = descripcionrol;
	}

	public Rol(BigDecimal rolid, String nombrerol, String descripcionrol, Set<Usuario> usuarios) {
		this.rolid = rolid;
		this.nombrerol = nombrerol;
		this.descripcionrol = descripcionrol;
		this.usuarios = usuarios;
	}

	public BigDecimal getRolid() {
		return this.rolid;
	}

	public void setRolid(BigDecimal rolid) {
		this.rolid = rolid;
	}

	public String getNombrerol() {
		return this.nombrerol;
	}

	public void setNombrerol(String nombrerol) {
		this.nombrerol = nombrerol;
	}

	public String getDescripcionrol() {
		return this.descripcionrol;
	}

	public void setDescripcionrol(String descripcionrol) {
		this.descripcionrol = descripcionrol;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
