package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * Subgruposuelo generated by hbm2java
 */
public class Subgruposuelo implements java.io.Serializable {

	private BigDecimal subgrupoid;
	private Subordensuelo subordensuelo;
	private String nombre;
	private String descripcion;

	public Subgruposuelo() {
	}

	public Subgruposuelo(BigDecimal subgrupoid, String nombre, String descripcion) {
		this.subgrupoid = subgrupoid;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Subgruposuelo(BigDecimal subgrupoid, Subordensuelo subordensuelo, String nombre, String descripcion) {
		this.subgrupoid = subgrupoid;
		this.subordensuelo = subordensuelo;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public BigDecimal getSubgrupoid() {
		return this.subgrupoid;
	}

	public void setSubgrupoid(BigDecimal subgrupoid) {
		this.subgrupoid = subgrupoid;
	}

	public Subordensuelo getSubordensuelo() {
		return this.subordensuelo;
	}

	public void setSubordensuelo(Subordensuelo subordensuelo) {
		this.subordensuelo = subordensuelo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
