package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipopermeabilidad generated by hbm2java
 */
public class Tipopermeabilidad implements java.io.Serializable {

	private BigDecimal tipoperid;
	private String nombretipoper;
	private Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums = new HashSet<NivelhumTipopermeaGrupohum>(0);

	public Tipopermeabilidad() {
	}

	public Tipopermeabilidad(BigDecimal tipoperid, String nombretipoper) {
		this.tipoperid = tipoperid;
		this.nombretipoper = nombretipoper;
	}

	public Tipopermeabilidad(BigDecimal tipoperid, String nombretipoper,
			Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums) {
		this.tipoperid = tipoperid;
		this.nombretipoper = nombretipoper;
		this.nivelhumTipopermeaGrupohums = nivelhumTipopermeaGrupohums;
	}

	public BigDecimal getTipoperid() {
		return this.tipoperid;
	}

	public void setTipoperid(BigDecimal tipoperid) {
		this.tipoperid = tipoperid;
	}

	public String getNombretipoper() {
		return this.nombretipoper;
	}

	public void setNombretipoper(String nombretipoper) {
		this.nombretipoper = nombretipoper;
	}

	public Set<NivelhumTipopermeaGrupohum> getNivelhumTipopermeaGrupohums() {
		return this.nivelhumTipopermeaGrupohums;
	}

	public void setNivelhumTipopermeaGrupohums(Set<NivelhumTipopermeaGrupohum> nivelhumTipopermeaGrupohums) {
		this.nivelhumTipopermeaGrupohums = nivelhumTipopermeaGrupohums;
	}

}
