package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Zonavariedad generated by hbm2java
 */
public class Zonavariedad implements java.io.Serializable {

	private BigDecimal zonavarid;
	private String nombreznvar;
	private String descripcionznvar;
	private Set<ZonaagroZonavariedad> zonaagroZonavariedads = new HashSet<ZonaagroZonavariedad>(0);

	public Zonavariedad() {
	}

	public Zonavariedad(BigDecimal zonavarid, String nombreznvar, String descripcionznvar) {
		this.zonavarid = zonavarid;
		this.nombreznvar = nombreznvar;
		this.descripcionznvar = descripcionznvar;
	}

	public Zonavariedad(BigDecimal zonavarid, String nombreznvar, String descripcionznvar,
			Set<ZonaagroZonavariedad> zonaagroZonavariedads) {
		this.zonavarid = zonavarid;
		this.nombreznvar = nombreznvar;
		this.descripcionznvar = descripcionznvar;
		this.zonaagroZonavariedads = zonaagroZonavariedads;
	}

	public BigDecimal getZonavarid() {
		return this.zonavarid;
	}

	public void setZonavarid(BigDecimal zonavarid) {
		this.zonavarid = zonavarid;
	}

	public String getNombreznvar() {
		return this.nombreznvar;
	}

	public void setNombreznvar(String nombreznvar) {
		this.nombreznvar = nombreznvar;
	}

	public String getDescripcionznvar() {
		return this.descripcionznvar;
	}

	public void setDescripcionznvar(String descripcionznvar) {
		this.descripcionznvar = descripcionznvar;
	}

	public Set<ZonaagroZonavariedad> getZonaagroZonavariedads() {
		return this.zonaagroZonavariedads;
	}

	public void setZonaagroZonavariedads(Set<ZonaagroZonavariedad> zonaagroZonavariedads) {
		this.zonaagroZonavariedads = zonaagroZonavariedads;
	}

}
