package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * ZonaagroZonavariedad generated by hbm2java
 */
public class ZonaagroZonavariedad implements java.io.Serializable {

	private BigDecimal id;
	private Zonaagroecologica zonaagroecologica;
	private Zonavariedad zonavariedad;

	public ZonaagroZonavariedad() {
	}

	public ZonaagroZonavariedad(BigDecimal id) {
		this.id = id;
	}

	public ZonaagroZonavariedad(BigDecimal id, Zonaagroecologica zonaagroecologica, Zonavariedad zonavariedad) {
		this.id = id;
		this.zonaagroecologica = zonaagroecologica;
		this.zonavariedad = zonavariedad;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Zonaagroecologica getZonaagroecologica() {
		return this.zonaagroecologica;
	}

	public void setZonaagroecologica(Zonaagroecologica zonaagroecologica) {
		this.zonaagroecologica = zonaagroecologica;
	}

	public Zonavariedad getZonavariedad() {
		return this.zonavariedad;
	}

	public void setZonavariedad(Zonavariedad zonavariedad) {
		this.zonavariedad = zonavariedad;
	}

}
