package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;

/**
 * ZonaagroecologicaIngenio generated by hbm2java
 */
public class ZonaagroecologicaIngenio implements java.io.Serializable {

	private BigDecimal id;
	private Ingenio ingenio;
	private Zonaagroecologica zonaagroecologica;

	public ZonaagroecologicaIngenio() {
	}

	public ZonaagroecologicaIngenio(BigDecimal id) {
		this.id = id;
	}

	public ZonaagroecologicaIngenio(BigDecimal id, Ingenio ingenio, Zonaagroecologica zonaagroecologica) {
		this.id = id;
		this.ingenio = ingenio;
		this.zonaagroecologica = zonaagroecologica;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Ingenio getIngenio() {
		return this.ingenio;
	}

	public void setIngenio(Ingenio ingenio) {
		this.ingenio = ingenio;
	}

	public Zonaagroecologica getZonaagroecologica() {
		return this.zonaagroecologica;
	}

	public void setZonaagroecologica(Zonaagroecologica zonaagroecologica) {
		this.zonaagroecologica = zonaagroecologica;
	}

}
