package co.edu.icesi.demo.modelo;
// Generated 18/05/2017 01:24:35 PM by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Zonaagroecologica generated by hbm2java
 */
public class Zonaagroecologica implements java.io.Serializable {

	private String zonaagroid;
	private Grupohomogeneosuelo grupohomogeneosuelo;
	private Grupohumedad grupohumedad;
	private String codigoznagro;
	private Set<Diagnosticoagronomo> diagnosticoagronomos = new HashSet<Diagnosticoagronomo>(0);
	private Set<ZonaagroZonavariedad> zonaagroZonavariedads = new HashSet<ZonaagroZonavariedad>(0);
	private Set<ZonaagroecologicaIngenio> zonaagroecologicaIngenios = new HashSet<ZonaagroecologicaIngenio>(0);

	public Zonaagroecologica() {
	}

	public Zonaagroecologica(String zonaagroid, String codigoznagro) {
		this.zonaagroid = zonaagroid;
		this.codigoznagro = codigoznagro;
	}

	public Zonaagroecologica(String zonaagroid, Grupohomogeneosuelo grupohomogeneosuelo, Grupohumedad grupohumedad,
			String codigoznagro, Set<Diagnosticoagronomo> diagnosticoagronomos,
			Set<ZonaagroZonavariedad> zonaagroZonavariedads, Set<ZonaagroecologicaIngenio> zonaagroecologicaIngenios) {
		this.zonaagroid = zonaagroid;
		this.grupohomogeneosuelo = grupohomogeneosuelo;
		this.grupohumedad = grupohumedad;
		this.codigoznagro = codigoznagro;
		this.diagnosticoagronomos = diagnosticoagronomos;
		this.zonaagroZonavariedads = zonaagroZonavariedads;
		this.zonaagroecologicaIngenios = zonaagroecologicaIngenios;
	}

	public String getZonaagroid() {
		return this.zonaagroid;
	}

	public void setZonaagroid(String zonaagroid) {
		this.zonaagroid = zonaagroid;
	}

	public Grupohomogeneosuelo getGrupohomogeneosuelo() {
		return this.grupohomogeneosuelo;
	}

	public void setGrupohomogeneosuelo(Grupohomogeneosuelo grupohomogeneosuelo) {
		this.grupohomogeneosuelo = grupohomogeneosuelo;
	}

	public Grupohumedad getGrupohumedad() {
		return this.grupohumedad;
	}

	public void setGrupohumedad(Grupohumedad grupohumedad) {
		this.grupohumedad = grupohumedad;
	}

	public String getCodigoznagro() {
		return this.codigoznagro;
	}

	public void setCodigoznagro(String codigoznagro) {
		this.codigoznagro = codigoznagro;
	}

	public Set<Diagnosticoagronomo> getDiagnosticoagronomos() {
		return this.diagnosticoagronomos;
	}

	public void setDiagnosticoagronomos(Set<Diagnosticoagronomo> diagnosticoagronomos) {
		this.diagnosticoagronomos = diagnosticoagronomos;
	}

	public Set<ZonaagroZonavariedad> getZonaagroZonavariedads() {
		return this.zonaagroZonavariedads;
	}

	public void setZonaagroZonavariedads(Set<ZonaagroZonavariedad> zonaagroZonavariedads) {
		this.zonaagroZonavariedads = zonaagroZonavariedads;
	}

	public Set<ZonaagroecologicaIngenio> getZonaagroecologicaIngenios() {
		return this.zonaagroecologicaIngenios;
	}

	public void setZonaagroecologicaIngenios(Set<ZonaagroecologicaIngenio> zonaagroecologicaIngenios) {
		this.zonaagroecologicaIngenios = zonaagroecologicaIngenios;
	}

}
