//created on: 01/06/2017

package com.expertofertilizacion.drools



//list any import classes here.
import com.expertofertilizacion.drools.model.*

// Reglas de configuraciones iniciales.

rule "0"
    when
        $as : AnalisisDeSuelo(ph>=7.2)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> ph: ALCALINO");

end

rule "1"
    when
        $as : AnalisisDeSuelo( ph>6.8 && ph <7.2)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> ph: LIGERAMENTE ALCALINO");

end

rule "2"
    when
        $as : AnalisisDeSuelo( ph<=6.8 && ph >=6.2)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> ph: NEUTRO");

end


rule "3"
    when
        $as : AnalisisDeSuelo( ph>5.6 && ph <6.2)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> ph: LIGERAMENTE ACIDO");

end

rule "4"
    when
        $as : AnalisisDeSuelo( ph <=5.6)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> ph: ACIDO");

end


rule "5"
    when
        $as : AnalisisDeSuelo( conductividadElectrica < 0.8)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> conductividadElectrica: BAJA");

end

rule "6"
    when
        $as : AnalisisDeSuelo( conductividadElectrica >= 0.8)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> conductividadElectrica: ALTA");

end

rule "7"
    when
        $as : AnalisisDeSuelo( PH == ALCALINO )               
    then
		System.out.println("\n\n\n");
        System.out.println("==> ExtractoSoluble: True");

end

rule "8"
    when
        $as : AnalisisDeSuelo( PH == LIGERAMENTE ALCALINO )               
    then
		System.out.println("\n\n\n");
        System.out.println("==> ExtractoSoluble: True");
		
end

rule "9"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == ALCALINO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Baja mineralizacion de MO (Baja actvidad microbiologica");
        System.out.println("     |-(4) Acumulacion de iones alcalinoterreos	");
        
        Fire Rule : CalcularIntercambiables;
        		
end

rule "10"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == ALCALINO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError1();
       		
end

rule "11"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == ALCALINO && conductividadElectrica == ALTA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Coloraciones grises suelo (Glaizeado)");
        System.out.println("     |-(2) Suelo Hidromorfico");    
        System.out.println("     |-(3) Limitaciones fisicas temporales");
        System.out.println("     |-(4) Baja difusion de Oxigeno y flujo de gases");
        Fire Rule : CalcularIntercambiables;		
end

rule "12"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == ALCALINO && conductividadElectrica == ALTA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.revisarMenores();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");  
        
        Fire Rule : CalcularIntercambiables;          		
end

rule "13"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == ALCALINO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Baja mineralizacion de MO (Baja actvidad microbiologica");
        System.out.println("     |-(4) Acumulacion de iones alcalinoterreos	");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
       
       	Fire Rule : CalcularIntercambiables;	
        		
end

rule "14"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == ALCALINO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError1();
       		
end

rule "15"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == ALCALINO && conductividadElectrica == BAJA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Coloraciones grises suelo (Glaizeado)");
        System.out.println("     |-(2) Suelo Hidromorfico");    
        System.out.println("     |-(3) Limitaciones fisicas temporales");
        System.out.println("     |-(4) Baja difusion de Oxigeno y flujo de gases");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
        		
        Fire Rule : CalcularIntercambiables;
end

rule "16"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == ALCALINO && conductividadElectrica == ALTA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.revisarMenores();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");   
        System.out.println("     |-(3) Baja disponibilidad de elementos menores "); 
        
        Fire Rule : CalcularIntercambiables;
        		
end

rule "17"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Baja mineralizacion de MO (Baja actvidad microbiologica");
        System.out.println("     |-(4) Acumulacion de iones alcalinoterreos	");
        System.out.println("     |-(5) Alta saturación de calcio");
        System.out.println("     |-(6) Salinidad en el suelo");
        System.out.println("     |-(7) Baja disponibilidad de Fosforo (Precipitación)");
            
        Fire Rule : CalcularIntercambiables;
        Fire Rule : Enmienda;	
end

rule "18"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError1();
       		
end

rule "19"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == ALTA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Coloraciones grises suelo (Glaizeado)");
        System.out.println("     |-(2) Suelo Hidromorfico");    
        System.out.println("     |-(3) Limitaciones fisicas temporales");
        System.out.println("     |-(4) Baja difusion de Oxigeno y flujo de gases");
        Fire Rule : CalcularIntercambiables;		
end

rule "20"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == ALTA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.revisarMenores();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");  
        
        Fire Rule : CalcularIntercambiables;          		
end

rule "21"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Baja mineralizacion de MO (Baja actvidad microbiologica");
        System.out.println("     |-(4) Acumulacion de iones alcalinoterreos	");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
       
       	Fire Rule : CalcularIntercambiables;	
        		
end

rule "22"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError1();
       		
end

rule "23"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == BAJA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Coloraciones grises suelo (Glaizeado)");
        System.out.println("     |-(2) Suelo Hidromorfico");    
        System.out.println("     |-(3) Limitaciones fisicas temporales");
        System.out.println("     |-(4) Baja difusion de Oxigeno y flujo de gases");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
        		
        Fire Rule : CalcularIntercambiables;
end

rule "24"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == LIGERAMENTE ALCALINO && conductividadElectrica == ALTA)               
    then
			System.out.println("\n\n\n");
		
		$es: ExtractoSoluble.calcularRAS();
		$es: ExtractoSoluble.revisarMenores();
		$es: ExtractoSoluble.calcularElementos();
		
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");   
        System.out.println("     |-(3) Baja disponibilidad de elementos menores "); 
        
        Fire Rule : CalcularIntercambiables;
        		
end

rule "25"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == NEUTRO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
				
        System.out.println("     |-(1) Baja mineralizacion de MO (Baja actvidad microbiologica)	");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Salinidad en el suelo");
        
        Fire Rule : CalcularIntercambiables;
        		
end

rule "26"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == NEUTRO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError2();
       		
end

rule "27"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == NEUTRO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");

        System.out.println("     |-(1) Salinidad en el suelo);
        Fire Rule : CalcularIntercambiables;		
end

rule "28"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == NEUTRO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
        Fire Rule : CalcularIntercambiables;          		
end

rule "29"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == NEUTRO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");
				
        System.out.println("     |-(1) Baja mineralizacion de MO (Baja actvidad microbiologica)	");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Limitaciones de movimiento de agua");
        
      		
       	Fire Rule : CalcularIntercambiables;	
        		
end

rule "30"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == NEUTRO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError2();
       		
end

rule "31"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == NEUTRO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");
			
        System.out.println("     |-(1) Coloraciones grises suelo (Glaizeado)");
        Fire Rule : CalcularIntercambiables;
end

rule "32"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == NEUTRO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
				
        Fire Rule : CalcularIntercambiables;
        		
end

rule "33"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Baja mineralizacion de MO (Baja actvidad microbiologica");
        System.out.println("     |-(4) Acumulacion de iones alcalinoterreos	");
        System.out.println("     |-(5) Alta saturación de calcio");
        System.out.println("     |-(6) Salinidad en el suelo");
        System.out.println("     |-(7) Baja disponibilidad de Fosforo (Precipitación)");
            
        Fire Rule : CalcularIntercambiables;
        Fire Rule : Enmienda;	
end

rule "34"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError1();
       		
end

rule "35"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Contenido de Aluminio");
        System.out.println("     |-(2) Sulfatos altos");    
        System.out.println("     |-(3) Impedancia");
        Fire Rule : CalcularIntercambiables;		
end

rule "36"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");  
        
        Fire Rule : CalcularIntercambiables;          		
end

rule "37"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");

        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Baja mineralizacion de MO (Baja actvidad microbiologica");
        System.out.println("     |-(4) Acumulacion de iones alcalinoterreos	");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
       
       	Fire Rule : CalcularIntercambiables;	
        		
end

rule "38"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError1();
       		
end

rule "39"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Coloraciones grises suelo (Glaizeado)");
        System.out.println("     |-(2) Suelo Hidromorfico");    
        System.out.println("     |-(3) Limitaciones fisicas temporales");
        System.out.println("     |-(4) Baja difusion de Oxigeno y flujo de gases");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
        		
        Fire Rule : CalcularIntercambiables;
end

rule "40"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == LIGERAMENTE ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
			
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");   
        System.out.println("     |-(3) Baja disponibilidad de elementos menores "); 
        
        Fire Rule : CalcularIntercambiables;
        		
end

rule "41"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Acumulacion de iones alcalinoterreos	");
        System.out.println("     |-(4) Salinidad en el suelo");
        System.out.println("     |-(5) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(6) Baja disponibilidad de Calcio");
        System.out.println("     |-(7) Contenido de Aluminio");
        	
            
        Fire Rule : CalcularIntercambiables;
        Fire Rule : Enmienda;	
end

rule "42"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError();
       		
end

rule "43"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH ==  ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Contenido de Aluminio");
        System.out.println("     |-(2) Sulfatos altos");    
        System.out.println("     |-(3) Impedancia");
        Fire Rule : CalcularIntercambiables;		
end

rule "44"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");  
        
        Fire Rule : CalcularIntercambiables;          		
end

rule "45"
    when
        $as : AnalisisDeSuelo( arcilla >= 40.0 && PH == ACIDO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");

        System.out.println("     |-(1) Limitaciones de movimiento de agua");
        System.out.println("     |-(2) Baja difusion de Oxigeno y flujo de gases");    
        System.out.println("     |-(3) Baja mineralizacion de MO (Baja actvidad microbiologica");
        System.out.println("     |-(4) Acumulacion de iones alcalinoterreos	");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
       
       	Fire Rule : CalcularIntercambiables;	
        		
end

rule "46"
    when
        $as : AnalisisDeSuelo( arena >= 50.0 && PH == ACIDO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");	
        System.out.println("     |-(1) Revisar las mediciones realizadas.");
        $as : AnalisisDeSuelo.showError1();
       		
end

rule "47"
    when
        $as : AnalisisDeSuelo( limo >= 45.0 && PH == ACIDO && conductividadElectrica == BAJA)               
    then
		System.out.println("\n\n\n");
		
        System.out.println("     |-(1) Coloraciones grises suelo (Glaizeado)");
        System.out.println("     |-(2) Suelo Hidromorfico");    
        System.out.println("     |-(3) Limitaciones fisicas temporales");
        System.out.println("     |-(4) Baja difusion de Oxigeno y flujo de gases");
        System.out.println("     |-(5) Baja disponibilidad de elementos menores ");
        		
        Fire Rule : CalcularIntercambiables;
end

rule "48"
    when
        $as : AnalisisDeSuelo( limo <= 40.0 &&  arena <= 40.0 && arcilla <= 40.0 && PH == ACIDO && conductividadElectrica == ALTA)               
    then
		System.out.println("\n\n\n");
			
        System.out.println("     |-(1) Baja disponibilidad de Fosforo (Precipitación)");
        System.out.println("     |-(2) Baja disponibilidad de Calcio");   
        System.out.println("     |-(3) Baja disponibilidad de elementos menores "); 
        
        Fire Rule : CalcularIntercambiables;
        		
end


rule "CalcularIntercambiables"

		$ei: ExtractoIntercambiable.calcularElementos();
       		
end

rule "Enmienda"

		$as: AnalisisDeSuelo.calcularEnmienda();
       		
end

rule "Variedad"

		$as: data1.getVariedades();
       		
end

rule "Clima"

		$c: Clima.meteoBlueReport();
       		
end

rule "300"
    when
        $p : Planta(des==0)               
    then
		System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");
        System.out.println("     |-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");


end

rule "310"
    when
        $p : Planta(des==310)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("    >|-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");
        System.out.println("        |-(31)TALLITOS CUADRADOS O REDONDEADOS, BRÁCTEAS FLORALES");
        System.out.println("        |-(32)SEMEJANTE PERO SIN BRÁCTEAS, PELOS GRANDULÍFEROS");
        System.out.println("        |-(33)HOJAS ASERRADAS, AROMÁTICAS, FLOR EN PARAGÜITAS SOBRE CABECITAS");
        System.out.println("        |-(34)SIMILAR A LA ANTERIOR PERO FLORES EN FORMA DE LABIOS O TROMPETILLAS");
        System.out.println("        |-(35)PARECIDA A LAS ANTERIORES PERO LA MAYORÍA INODORAS");
        System.out.println("        |-(36)HOJAS PINTADAS DE ROJO O VIOLETA O TODAS COLOREADAS POR EL ENVÉS, FLORES TUBULARES ROJIZAS O AMARILLAS");
        System.out.println("        |-(37)HOJAS CURVINERVIAS, TALLOS CUADRADOS O REDONDOS, MUCHAS PELUDITAS");
        System.out.println("        |-(38)NUDOS ENGROSADOS, A VECES COLOREADOS, ENTERAS, NERVIOS POCO MARCADOS");
        System.out.println("        |-(39)HOJAS OPUESTAS O VERTICILADAS, CON TALLOS Y HOJAS CARNOSOS, FLOR EN CHURRUSCO");
        System.out.println("       >|-(310)HOJAS OPUESTAS O VERTICILADAS, RAÍZ CON OLOR A MENTOL");
        System.out.println("          >| |=><<<FAMILIA>>>: Polygalaceae \n");         
        System.out.println("     |-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");

end

rule "314"
    when
        $p : Planta(des==314)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");        
        System.out.println("    >|-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");
        System.out.println("        |-(41)ESTÍPULAS LIBRES, CORTEZA EN TIRAS LARGAS. HOJAS PENNI O PALMALOBULADAS, ASERRADAS");
        System.out.println("        |-(42)SEMEJANTE PERO CON PELOS ESTRELLADOS");
        System.out.println("        |-(43)ESTÍPULAS LIBRES, TALLOS Y HOJAS SUCULENTAS, BASE DE LA HOJA ASIMÉTRICA, MUCHAS COLOREADAS");
        System.out.println("        |-(44)ESTÍPULAS CILIADAS, HOJAS DE BORDE ASERRADO");
        System.out.println("        |-(45)ESTÍPULAS BAJANTES AL PECÍOLO O EN GORRITO, RAÍCES ADVENTICIAS, OLOROSAS");
        System.out.println("        |-(46)ESTIPULAS LIBRES, HOJAS DENTADAS O ASERRADAS CON TRES A CINCO NERVIOS BASALES, PELUDAS");

end



rule "341"
    when
        $p : Planta(des==341)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");        
        System.out.println("    >|-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");
        System.out.println("       >|-(41)ESTÍPULAS LIBRES, CORTEZA EN TIRAS LARGAS. HOJAS PENNI O PALMALOBULADAS, ASERRADAS");
        System.out.println("          >||=><<<FAMILIA>>>: Tiliaceae \n"); 
        System.out.println("        |-(42)SEMEJANTE PERO CON PELOS ESTRELLADOS");
        System.out.println("        |-(43)ESTÍPULAS LIBRES, TALLOS Y HOJAS SUCULENTAS, BASE DE LA HOJA ASIMÉTRICA, MUCHAS COLOREADAS");
        System.out.println("        |-(44)ESTÍPULAS CILIADAS, HOJAS DE BORDE ASERRADO");
        System.out.println("        |-(45)ESTÍPULAS BAJANTES AL PECÍOLO O EN GORRITO, RAÍCES ADVENTICIAS, OLOROSAS");
        System.out.println("        |-(46)ESTIPULAS LIBRES, HOJAS DENTADAS O ASERRADAS CON TRES A CINCO NERVIOS BASALES, PELUDAS");

end

rule "342"
    when
        $p : Planta(des==342)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");        
        System.out.println("    >|-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");
        System.out.println("        |-(41)ESTÍPULAS LIBRES, CORTEZA EN TIRAS LARGAS. HOJAS PENNI O PALMALOBULADAS, ASERRADAS");
        System.out.println("       >|-(42)SEMEJANTE PERO CON PELOS ESTRELLADOS");
        System.out.println("          >||=><<<FAMILIA>>>: Malvaceae \n"); 
        System.out.println("        |-(43)ESTÍPULAS LIBRES, TALLOS Y HOJAS SUCULENTAS, BASE DE LA HOJA ASIMÉTRICA, MUCHAS COLOREADAS");
        System.out.println("        |-(44)ESTÍPULAS CILIADAS, HOJAS DE BORDE ASERRADO");
        System.out.println("        |-(45)ESTÍPULAS BAJANTES AL PECÍOLO O EN GORRITO, RAÍCES ADVENTICIAS, OLOROSAS");
        System.out.println("        |-(46)ESTIPULAS LIBRES, HOJAS DENTADAS O ASERRADAS CON TRES A CINCO NERVIOS BASALES, PELUDAS");

end

rule "343"
    when
        $p : Planta(des==343)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");        
        System.out.println("    >|-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");
        System.out.println("        |-(41)ESTÍPULAS LIBRES, CORTEZA EN TIRAS LARGAS. HOJAS PENNI O PALMALOBULADAS, ASERRADAS");
        System.out.println("        |-(42)SEMEJANTE PERO CON PELOS ESTRELLADOS");
        System.out.println("       >|-(43)ESTÍPULAS LIBRES, TALLOS Y HOJAS SUCULENTAS, BASE DE LA HOJA ASIMÉTRICA, MUCHAS COLOREADAS");
        System.out.println("          >||=><<<FAMILIA>>>: Begoniaceae \n"); 
        System.out.println("        |-(44)ESTÍPULAS CILIADAS, HOJAS DE BORDE ASERRADO");
        System.out.println("        |-(45)ESTÍPULAS BAJANTES AL PECÍOLO O EN GORRITO, RAÍCES ADVENTICIAS, OLOROSAS");
        System.out.println("        |-(46)ESTIPULAS LIBRES, HOJAS DENTADAS O ASERRADAS CON TRES A CINCO NERVIOS BASALES, PELUDAS");

end

rule "344"
    when
        $p : Planta(des==344)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");        
        System.out.println("    >|-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");
        System.out.println("        |-(41)ESTÍPULAS LIBRES, CORTEZA EN TIRAS LARGAS. HOJAS PENNI O PALMALOBULADAS, ASERRADAS");
        System.out.println("        |-(42)SEMEJANTE PERO CON PELOS ESTRELLADOS");
        System.out.println("        |-(43)ESTÍPULAS LIBRES, TALLOS Y HOJAS SUCULENTAS, BASE DE LA HOJA ASIMÉTRICA, MUCHAS COLOREADAS");
        System.out.println("       >|-(44)ESTÍPULAS CILIADAS, HOJAS DE BORDE ASERRADO");
        System.out.println("          >||=><<<FAMILIA>>>: Violaceae \n"); 
        System.out.println("        |-(45)ESTÍPULAS BAJANTES AL PECÍOLO O EN GORRITO, RAÍCES ADVENTICIAS, OLOROSAS");
        System.out.println("        |-(46)ESTIPULAS LIBRES, HOJAS DENTADAS O ASERRADAS CON TRES A CINCO NERVIOS BASALES, PELUDAS");

end

rule "345"
    when
        $p : Planta(des==345)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");        
        System.out.println("    >|-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");
        System.out.println("        |-(41)ESTÍPULAS LIBRES, CORTEZA EN TIRAS LARGAS. HOJAS PENNI O PALMALOBULADAS, ASERRADAS");
        System.out.println("        |-(42)SEMEJANTE PERO CON PELOS ESTRELLADOS");
        System.out.println("        |-(43)ESTÍPULAS LIBRES, TALLOS Y HOJAS SUCULENTAS, BASE DE LA HOJA ASIMÉTRICA, MUCHAS COLOREADAS");
        System.out.println("        |-(44)ESTÍPULAS CILIADAS, HOJAS DE BORDE ASERRADO");
        System.out.println("       >|-(45)ESTÍPULAS BAJANTES AL PECÍOLO O EN GORRITO, RAÍCES ADVENTICIAS, OLOROSAS");
        System.out.println("          >||=><<<FAMILIA>>>: Araceae \n"); 
        System.out.println("        |-(46)ESTIPULAS LIBRES, HOJAS DENTADAS O ASERRADAS CON TRES A CINCO NERVIOS BASALES, PELUDAS");

end

rule "346"
    when
        $p : Planta(des==346)               
    then
    	System.out.println("\n\n\n");
        System.out.println("==> (0)HERBÁCEAS");
        System.out.println("     |-(1) HOJAS COMPUESTAS, ALTERNAS");
        System.out.println("     |-(2) HOJAS SIMPLES OPUESTAS, CON ESTÍPULAS");    
        System.out.println("     |-(3) HOJAS SIMPLES, OPUESTAS, SIN ESTÍPULAS");        
        System.out.println("    >|-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS");
        System.out.println("        |-(41)ESTÍPULAS LIBRES, CORTEZA EN TIRAS LARGAS. HOJAS PENNI O PALMALOBULADAS, ASERRADAS");
        System.out.println("        |-(42)SEMEJANTE PERO CON PELOS ESTRELLADOS");
        System.out.println("        |-(43)ESTÍPULAS LIBRES, TALLOS Y HOJAS SUCULENTAS, BASE DE LA HOJA ASIMÉTRICA, MUCHAS COLOREADAS");
        System.out.println("        |-(44)ESTÍPULAS CILIADAS, HOJAS DE BORDE ASERRADO");
        System.out.println("        |-(45)ESTÍPULAS BAJANTES AL PECÍOLO O EN GORRITO, RAÍCES ADVENTICIAS, OLOROSAS");
        System.out.println("       >|-(46)ESTIPULAS LIBRES, HOJAS DENTADAS O ASERRADAS CON TRES A CINCO NERVIOS BASALES, PELUDAS");
        System.out.println("          >||=><<<FAMILIA>>>: Urticaceae \n"); 

end

     |-(4) HOJAS SIMPLES, ALTERNAS, CON ESTÍPULAS
end
